# Generated by Django 5.1.1 on 2026-03-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_userdata_emotions_and_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='anger',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='excitement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='frustration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
